/**
 * From https://nodejs.org/api/os.html#os_error_constants
 */

/**
 * Returns the meaning of the specified error code as a string
 *
 * @param code Either the enum code or its string form
 */
export function get_str(code: ePosix | keyof typeof ePosix): string {
  if (code as ePosix) {
    return posix[code];
  }
  return posix[ePosix[code]];
}

export enum ePosix {
  E2BIG,
  EACCES,
  EADDRINUSE,
  EADDRNOTAVAIL,
  EAFNOSUPPORT,
  EAGAIN,
  EALREADY,
  EBADF,
  EBADMSG,
  EBUSY,
  ECANCELED,
  ECHILD,
  ECONNABORTED,
  ECONNREFUSED,
  ECONNRESET,
  EDEADLK,
  EDESTADDRREQ,
  EDOM,
  EDQUOT,
  EEXIST,
  EFAULT,
  EFBIG,
  EHOSTUNREACH,
  EIDRM,
  EILSEQ,
  EINPROGRESS,
  EINTR,
  EINVAL,
  EIO,
  EISCONN,
  EISDIR,
  ELOOP,
  EMFILE,
  EMLINK,
  EMSGSIZE,
  EMULTIHOP,
  ENAMETOOLONG,
  ENETDOWN,
  ENETRESET,
  ENETUNREACH,
  ENFILE,
  ENOBUFS,
  ENODATA,
  ENODEV,
  ENOENT,
  ENOEXEC,
  ENOLCK,
  ENOLINK,
  ENOMEM,
  ENOMSG,
  ENOPROTOOPT,
  ENOSPC,
  ENOSR,
  ENOSTR,
  ENOSYS,
  ENOTCONN,
  ENOTDIR,
  ENOTEMPTY,
  ENOTSOCK,
  ENOTSUP,
  ENOTTY,
  ENXIO,
  EOPNOTSUPP,
  EOVERFLOW,
  EPERM,
  EPIPE,
  EPROTO,
  EPROTONOSUPPORT,
  EPROTOTYPE,
  ERANGE,
  EROFS,
  ESPIPE,
  ESRCH,
  ESTALE,
  ETIME,
  ETIMEDOUT,
  ETXTBSY,
  EWOULDBLOCK,
  EXDEV,
}

export const posix = {
  [ePosix.E2BIG]:
    "Indicates that the list of arguments is longer than expected.",
  [ePosix.EACCES]:
    "Indicates that the operation did not have sufficient permissions.",
  [ePosix.EADDRINUSE]: "Indicates that the network address is already in use.",
  [ePosix.EADDRNOTAVAIL]:
    "Indicates that the network address is currently unavailable for use.",
  [ePosix.EAFNOSUPPORT]:
    "Indicates that the network address family is not supported.",
  [ePosix.EAGAIN]:
    "Indicates that there is no data available and to try the operation again later.",
  [ePosix.EALREADY]:
    "Indicates that the socket already has a pending connection in progress.",
  [ePosix.EBADF]: "Indicates that a file descriptor is not valid.",
  [ePosix.EBADMSG]: "Indicates an invalid data message.",
  [ePosix.EBUSY]: "Indicates that a device or resource is busy.",
  [ePosix.ECANCELED]: "Indicates that an operation was canceled.",
  [ePosix.ECHILD]: "Indicates that there are no child processes.",
  [ePosix.ECONNABORTED]:
    "Indicates that the network connection has been aborted.",
  [ePosix.ECONNREFUSED]:
    "Indicates that the network connection has been refused.",
  [ePosix.ECONNRESET]: "Indicates that the network connection has been reset.",
  [ePosix.EDEADLK]: "Indicates that a resource deadlock has been avoided.",
  [ePosix.EDESTADDRREQ]: "Indicates that a destination address is required.",
  [ePosix.EDOM]:
    "Indicates that an argument is out of the domain of the function.",
  [ePosix.EDQUOT]: "Indicates that the disk quota has been exceeded.",
  [ePosix.EEXIST]: "Indicates that the file already exists.",
  [ePosix.EFAULT]: "Indicates an invalid pointer address.",
  [ePosix.EFBIG]: "Indicates that the file is too large.",
  [ePosix.EHOSTUNREACH]: "Indicates that the host is unreachable.",
  [ePosix.EIDRM]: "Indicates that the identifier has been removed.",
  [ePosix.EILSEQ]: "Indicates an illegal byte sequence.",
  [ePosix.EINPROGRESS]: "Indicates that an operation is already in progress.",
  [ePosix.EINTR]: "Indicates that a function call was interrupted.",
  [ePosix.EINVAL]: "Indicates that an invalid argument was provided.",
  [ePosix.EIO]: "Indicates an otherwise unspecified I/O error.",
  [ePosix.EISCONN]: "Indicates that the socket is connected.",
  [ePosix.EISDIR]: "Indicates that the path is a directory.",
  [ePosix.ELOOP]: "Indicates too many levels of symbolic links in a path.",
  [ePosix.EMFILE]: "Indicates that there are too many open files.",
  [ePosix.EMLINK]: "Indicates that there are too many hard links to a file.",
  [ePosix.EMSGSIZE]: "Indicates that the provided message is too long.",
  [ePosix.EMULTIHOP]: "Indicates that a multihop was attempted.",
  [ePosix.ENAMETOOLONG]: "Indicates that the filename is too long.",
  [ePosix.ENETDOWN]: "Indicates that the network is down.",
  [ePosix.ENETRESET]:
    "Indicates that the connection has been aborted by the network.",
  [ePosix.ENETUNREACH]: "Indicates that the network is unreachable.",
  [ePosix.ENFILE]: "Indicates too many open files in the system.",
  [ePosix.ENOBUFS]: "Indicates that no buffer space is available.",
  [ePosix.ENODATA]:
    "Indicates that no message is available on the stream head read queue.",
  [ePosix.ENODEV]: "Indicates that there is no such device.",
  [ePosix.ENOENT]: "Indicates that there is no such file or directory.",
  [ePosix.ENOEXEC]: "Indicates an exec format error.",
  [ePosix.ENOLCK]: "Indicates that there are no locks available.",
  [ePosix.ENOLINK]: "Indications that a link has been severed.",
  [ePosix.ENOMEM]: "Indicates that there is not enough space.",
  [ePosix.ENOMSG]: "Indicates that there is no message of the desired type.",
  [ePosix.ENOPROTOOPT]: "Indicates that a given protocol is not available.",
  [ePosix.ENOSPC]: "Indicates that there is no space available on the device.",
  [ePosix.ENOSR]: "Indicates that there are no stream resources available.",
  [ePosix.ENOSTR]: "Indicates that a given resource is not a stream.",
  [ePosix.ENOSYS]: "Indicates that a function has not been implemented.",
  [ePosix.ENOTCONN]: "Indicates that the socket is not connected.",
  [ePosix.ENOTDIR]: "Indicates that the path is not a directory.",
  [ePosix.ENOTEMPTY]: "Indicates that the directory is not empty.",
  [ePosix.ENOTSOCK]: "Indicates that the given item is not a socket.",
  [ePosix.ENOTSUP]: "Indicates that a given operation is not supported.",
  [ePosix.ENOTTY]: "Indicates an inappropriate I/O control operation.",
  [ePosix.ENXIO]: "Indicates no such device or address.",
  [ePosix.EOPNOTSUPP]:
    "Indicates that an operation is not supported on the socket. Although ENOTSUPand EOPNOTSUPP have the same value on Linux, according to POSIX.1 these error values should be distinct.)",
  [ePosix.EOVERFLOW]:
    "Indicates that a value is too large to be stored in a given data type.",
  [ePosix.EPERM]: "Indicates that the operation is not permitted.",
  [ePosix.EPIPE]: "Indicates a broken pipe.",
  [ePosix.EPROTO]: "Indicates a protocol error.",
  [ePosix.EPROTONOSUPPORT]: "Indicates that a protocol is not supported.",
  [ePosix.EPROTOTYPE]: "Indicates the wrong type of protocol for a socket.",
  [ePosix.ERANGE]: "Indicates that the results are too large.",
  [ePosix.EROFS]: "Indicates that the file system is read only.",
  [ePosix.ESPIPE]: "Indicates an invalid seek operation.",
  [ePosix.ESRCH]: "Indicates that there is no such process.",
  [ePosix.ESTALE]: "Indicates that the file handle is stale.",
  [ePosix.ETIME]: "Indicates an expired timer.",
  [ePosix.ETIMEDOUT]: "Indicates that the connection timed out.",
  [ePosix.ETXTBSY]: "Indicates that a text file is busy.",
  [ePosix.EWOULDBLOCK]: "Indicates that the operation would block.",
  [ePosix.EXDEV]: "Indicates an improper link.",
};
