import * as bool_1 from "./types/Bool.js";
export { bool_1 as bool };
import * as json_1 from "./obj/Json.js";
export { json_1 as json };
import * as text_1 from "./text/text.js";
export { text_1 as text };
import * as number_1 from "./number/number.js";
export { number_1 as number };
import * as types_1 from "./types/Type.js";
export { types_1 as types };
import * as obj_1 from "./obj/obj_entry.js";
export { obj_1 as obj };
import * as geo_1 from "./geo/geo.js";
export { geo_1 as geo };
import * as graphic_1 from "./graphic/graphic.js";
export { graphic_1 as graphic };
import * as regex_1 from "./regex/regex.js";
export { regex_1 as regex };
import * as date from "./time/Date.js";
export declare const time: {
    date: typeof date;
};
