/**
 * From https://gist.github.com/wpsmith/7604842
 */
export default {
    fr: "France",
    be: "Belgique",
    ca: "Canada",
    lu: "Luxembourg",
    mc: "Monaco",
    ch: "Suisse/Switzerland",
    au: "Australia",
    bz: "Belize",
    en: "England",
    gd: "Scotland",
    ie: "Ireland",
    jm: "Jamaica",
    nz: "New Zealand",
    ph: "Philippines",
    za: "South Africa",
    tt: "Trinidad & Tobago",
    gb: "United Kingdom",
    us: "United States",
    zw: "Zimbabwe",
    at: "Austria",
    de: "Germany",
    li: "Liechtenstein",
    it: "Italy",
    ar: "Argentina",
    bo: "Bolivia",
    cl: "Chile",
    co: "Colombia",
    cr: "Costa Rica",
    do: "Dominican Republic",
    ec: "Ecuador",
    sv: "El Salvador",
    gt: "Guatemala",
    hn: "Honduras",
    mx: "Mexico",
    ni: "Nicaragua",
    pa: "Panama",
    py: "Paraguay",
    pe: "Peru",
    pr: "Puerto Rico",
    es: "Spain",
    uy: "Uruguay",
    ve: "Venezuela",
    af: "Afrikaans",
    sq: "Albanian",
    an: "Aragonese",
    dz: "Algeria",
    bh: "Bahrain",
    eg: "Egypt",
    iq: "Iraq",
    jo: "Jordan",
    kw: "Kuwait",
    lb: "Lebanon",
    ly: "Libya",
    ma: "Morocco",
    om: "Oman",
    qa: "Qatar",
    sa: "Saudi Arabia",
    sy: "Syria",
    tn: "Tunisia",
    ae: "U.A.E.",
    ye: "Yemen",
    hy: "Armenian",
    as: "Assamese",
    ast: "Asturian",
    az: "Azerbaijani",
    es_eu: "Basque",
    bg: "Bulgarian",
    by: "Belarusian",
    bn: "Bengali",
    bs: "Bosnian",
    br: "Breton",
    my: "Burmese",
    es_ca: "Catalan",
    gu: "Chamorro",
    ce: "Chechen",
    zh: "China",
    hk: "Hong Kong",
    cn: "China PRC",
    sg: "Singapore",
    tw: "Taiwan",
    cv: "Chuvash",
    fr_co: "Corsican",
    cre: "Cree",
    hr: "Croatian",
    cs: "Czech Republic",
    da: "Danish",
    et: "Estonian",
    fo: "Faeroese",
    fa: "Farsi",
    fj: "Fijian",
    fi: "Finnish",
    fy: "Frisian",
    fur: "Friulian",
    gl: "Galacian",
    ka: "Georgian",
    el: "Greek",
    guj: "Gujurati",
    ht: "Haitian",
    he: "Hebrew",
    hi: "Hindi",
    hu: "Hungarian",
    is: "Icelandic",
    id: "Indonesian",
    iu: "Inuktitut",
    ja: "Japan",
    kn: "Kannada",
    ks: "Kashmiri",
    kk: "Kazakh",
    km: "Khmer",
    ky: "Kirghiz",
    tlh: "Klingon",
    kp: "North Korea",
    kr: "South Korea",
    lv: "Latvian",
    lt: "Lithuanian",
    mk: "FYRO Macedonian",
    ms: "Malay",
    ml: "Malayalam",
    mt: "Maltese",
    mi: "Maori",
    mr: "Marathi",
    mo: "Moldavian",
    nv: "Navajo",
    ng: "Ndonga",
    ne: "Nepali",
    no: "Norwegian",
    nb: "Norwegian (Bokmal)",
    nn: "Norwegian (Nynorsk)",
    oc: "Occitan",
    or: "Oriya",
    orm: "Oromo",
    irn: "Persian",
    "fa-ir": "Persian/Iran",
    pl: "Polish",
    pt: "Portuguese",
    bra: "Brazil",
    in: "India",
    pk: "Pakistan",
    qu: "Quechua",
    rm: "Rhaeto-Romanic",
    ro: "Romany",
    md: "Moldavia",
    ru: "Russia",
    sz: "Sami (Lappish)",
    sag: "Sango",
    san: "Sanskrit",
    sc: "Sardinian",
    sct: "Scots Gaelic",
    sd: "Sindhi",
    si: "Singhalese",
    sr: "Serbian",
    sk: "Slovak",
    sl: "Slovenian",
    so: "Somani",
    sb: "Sorbian",
    sx: "Sutu",
    sw: "Swahili",
    fin: "Finland",
    se: "Sweden",
    ta: "Tamil",
    crh: "Tatar",
    te: "Teluga",
    th: "Thai",
    tig: "Tigre",
    ts: "Tsonga",
    tsn: "Tswana",
    tr: "Turkish",
    tk: "Turkmen",
    uk: "Ukrainian",
    hsb: "Upper Sorbian",
    ur: "Urdu",
    ven: "Venda",
    vi: "Vietnam",
    vo: "Volapuk",
    wa: "Walloon",
    cy: "Welsh",
    xh: "Xhosa",
    ji: "Yiddish",
    zu: "Zulu",
};
//# sourceMappingURL=country_codes.js.map