/**
 * Count the number of UTF-8 characters represented into the string,
 * for example characters generated by encodeURI
 * @param {*} str
 */
export declare function count_utf8_characters(str: string): number;
export declare function has_special_characters(str: string): boolean;
/**
 * Return val if it is a string or String,
 * null otherwise
 * @param val
 *
 * @return {string|String|null}
 */
export declare function if_is(val: any): string | String;
/**
 * Return if obj is a string/String or not
 * @param {*} val
 */
export declare function is(val: any): boolean;
/**
 * Return the number of occurences
 * of the specified regex
 * in the specified string
 * @param regex
 * @param str
 */
export declare function nb_occurences(regex: RegExp, str: string): number;
/**
 * Remove starting and ending spaces in str and return the result
 * @param str
 */
export declare function remove_enclosing_spaces(str: string): string;
/**
 * Convert specified value to string
 * @param {*} obj
 *
 * @return {string | null} Return null if failed converting to string
 */
export declare function to(obj: any): string;
export declare function random(length: number): string;
